[phases.setup]
nixPkgs = ["ffmpeg", "python311", "libsodium", "python311Packages.pynacl", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python3 bot.py"