[phases.setup]
nixPkgs = ["ffmpeg", "python311", "libsodium"]

[phases.install]
cmds = [
  "pip3 install -r requirements.txt",
  "pip3 install PyNaCl --no-binary PyNaCl"
]

[phases.start]
cmd = "python3 bot.py"