[phases.setup]
nixPkgs = ["ffmpeg", "libsodium", "python311Full"]

[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && pip install PyNaCl --no-binary PyNaCl --force-reinstall"
]

[phases.start]
cmd = ". /opt/venv/bin/activate && python3 bot.py"